#name, main, version and api are required
name: World1-6Ess
main: World16.World16.World16.Main
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0.0"
api: ["1.0.5"]
author: Nukkit Project
# Authors and author will be added together in one list.
authors: ["Example", "Another"]
description: Example plugin showing the API
website: https://github.com/NukkitX/ExamplePlugin
# These dependencies are required for the plugin to start.
#depend: ["OtherPlugin", "ThisPlugin"]
# These dependencies are not required.
# Log prefix in console
# Plugin will be loaded before these. Any cyclic loadbefore's or dependencies's will throw errors!